# --- Backend & Performance ---
backend = "glx";
vsync = true;
glx-no-rebind-pixmap = true;
use-damage = true;


# --- Shadows ---
shadow = false;
shadow-radius = 12;
shadow-opacity = 0.75;
shadow-offset-x = -12;
shadow-offset-y = -12;
# TODO: change this
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'i3-frame'",      # Prevents double-shadows on i3 containers
  "_GTK_FRAME_EXTENTS@:c",     # Fixes thick shadows on GTK3 apps
  "class_g = 'Polybar'",
  "class_g = 'i3bar'"
];


# --- Fading ---
fading = true;
fade-in-step = 0.5;
fade-out-step = 0.5;
fade-delta = 5;


# --- Opacity ---
inactive-opacity = 0.75;
frame-opacity = 1.0;
inactive-opacity-override = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];


# --- Corners ---
corner-radius = 7;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
