
"Remove ErrorBells and VisualBells (annoying)
set noeb vb t_vb=

set noshowmode                       "Mode already shown by lightline

"Set gui cursor
set guicursor+=a:blinkon0
"Set GUI options
set guioptions+=a                    "Vis selection goes to clipboard
set guioptions+=e                    "Better looking window tabs
set guioptions+=L                    "Remove left-hand scroll
set guioptions-=m                    "Remove menubar
set guioptions-=T                    "Remove toolbar
set guifont=Monospace\ 12
set lines=120 columns=240
