[colors]
primary = #008080
secondary = #f0c674
background = #1e222a
background-alt = #243335
foreground = #ffffff
warn = #FFFF10
alert = #e57373
disabled = #666666



[bar/main]
width = 100%
height = 24pt
radius = 0
top = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 5pt

padding-left = 1
padding-right = 1
module-margin = 1

separator = "|"
separator-foreground = ${colors.disabled}

font-0 = "DejaVu Sans Mono:size=12;1"

modules-left = i3
modules-right = filesystem cpu memory tray date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true



[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true

# Active Workspace
label-focused = %name%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.secondary}
label-focused-padding = 1

# Inactive Workspace
label-unfocused =
label-unfocused-padding = 1

# Urgent Workspace
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; [module/xwindow]
; type = internal/xwindow
; label = %title:0:35:...%
; label-foreground = ${colors.secondary}



[module/filesystem]
type = internal/fs
interval = 30

label-mounted = %{A1:nemo:} %{F#F0C674}%mountpoint%:%{F-} %free% left%{A}
mount-0 = /



[module/cpu]
type = internal/cpu
interval = 2
label = %{A1:gnome-system-monitor --show-processes-tab:}%{F#F0C674}CPU:%{F-} %percentage%%%{A}



[module/memory]
type = internal/memory
interval = 2

format = %{A1:gnome-system-monitor --show-processes-tab:}%{F#F0C674}RAM:%{F-} %{F<ramp-used>}<label>%{F-}%{A}
label = %free%

ramp-used-0 =
ramp-used-1 =
ramp-used-2 =
ramp-used-3 =
ramp-used-4 =
ramp-used-5 =
ramp-used-6 =
ramp-used-7 =
ramp-used-8 = ${colors.warn}
ramp-used-9 = ${colors.alert}
ramp-used-10 = ${colors.alert}



[module/date]
type = internal/date
interval = 60

# Formatting string for DD.MM.YYYY HH:MM
date = %d.%m.%Y %H:%M

label = %{A1:gsimplecal:}%date%%{A}
label-foreground = ${colors.secondary}



[module/tray]
type = internal/tray
tray-spacing = 8px
tray-size = 16px
