#
# ~/.bashrc
#

[[ $- != *i* ]] && return

colors() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}

[[ -f ~/.extend.bashrc ]] && . ~/.extend.bashrc

[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion




# [ENV VARIABLES]

# Prevents single command to flood the history
export HISTCONTROL=ignoredups
#PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"
#export PATH
export EDITOR="/usr/bin/vim"
# Set environment variables to scale QT applications
export QT_AUTO_SCREEN_FACTOR=1



# [ALIASES]
# Utils
alias ls='ls -F --color=always'
alias entar='tar -cvzf'
alias untar='tar -xvzf'
alias findkey='xev -event keyboard &'
alias showmimes='cat /usr/share/applications/mimeinfo.cache'
alias pacman='pacman --color always'

# Applications
alias browse='firefox &'
alias ffx='firefox &'
alias spotify='spotify --force-device-scale-factor=2 &'

# Gotos
alias godocs='cd ~/Documents'
alias godown='cd ~/Downloads'
alias gopics='cd ~/Pictures'
alias goscrs='cd ~/Screenshots'

# logout and lock require lightdm (or at least dm-tool)
alias lock='light-locker-command -l'
alias off='poweroff'
alias res='reboot'

open () { xdg-open "$1" & };
# Open man pages in vim
vimman () { man "$1" | vim -; }
gvimman () { man "$1" | gvim -; }
